#!/usr/bin/env bash
set -eux
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd libevent*
    make V=0 -s -i clean || true
    make V=0 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz -O sources.tar.gz
    tar -xf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd libevent*

cp $COSMOS/common.cache ./config.cache
./configure --cache-file=config.cache --prefix=$COSMOS\
    --disable-shared --disable-dependency-tracking\
    --disable-silent-rules --without-pic\
    --disable-libevent-regress --disable-verbose-debug\
    --disable-samples\
    --disable-malloc-replacement --disable-openssl\
    --disable-debug-mode --enable-function-sections\
    --build=$ARCH-linux-gnu

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
