#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="gdbm-1.23"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make V=0 -s -i clean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/gdbm/gdbm-1.23.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i
fi

# go into the source folder, configure
cd "$FOLDER"
export COMPATINCLUDEDIR="$COSMOS/include/gdbm"

cp ../saved_config.cache ./config.cache
./configure --cache-file=config.cache --prefix="$COSMOS"\
    --disable-memory-mapped-io --enable-libgdbm-compat\
    --disable-shared --enable-static\
    --disable-nls --disable-rpath\
    --without-pic --with-gnu-ld --without-readline\
    --sysconfdir=/zip --datarootdir=/zip/usr/share\
    CFLAGS="-Os"

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
