#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd curl*/
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://github.com/curl/curl/releases/download/curl-8_4_0/curl-8.4.0.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd curl*/
./configure --prefix="$COSMOS"\
    --enable-shared=no --enable-static=yes\
    --enable-pthreads --with-openssl=$COSMOS\
    --without-pic --with-gnu-ld\
    CFLAGS="-Os"

# run make and/or make install
make -s -j2
make install -s -j2

echo "DONE."
