#!/usr/bin/env bash
set -e
shopt -s expand_aliases
export COSMOPOLITAN_DISABLE_ZIPOS=1

ARCH="${ARCH:-x86_64}"

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd nettle*
    make -s -i distclean || true
    make -s -i clean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/nettle/nettle-3.9.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd nettle*
export GOBJECT_LIBS=""
export PKG_CONFIG=""

./configure --disable-shared --enable-fat\
    --disable-openssl --disable-assembler\
    --libdir="$COSMOS/lib" --prefix="$COSMOS"\
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
