#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

# download the source code
wget https://sourceforge.net/projects/libuuid/files/libuuid-1.0.3.tar.gz/download -O sources.tar.gz
tar -xzf sources.tar.gz

# apply patches if any
patch -p0 -i ./minimal.diff

# go into the source folder, configure
cd libuuid*/
./configure --enable-static --disable-shared\
    --without-pic --with-gnu-ld\
    --prefix="$COSMOS"\
    CFLAGS="-Os"

# run make and/or make install
make -j2
make install -j2

echo "DONE."
