#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="libuuid*"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd libuuid*
    make -s -i clean
    cd ..
else
    # download the source code
    wget -q https://sourceforge.net/projects/libuuid/files/libuuid-1.0.3.tar.gz/download -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i ./minimal.diff
fi

# go into the source folder, configure
cd libuuid*
./configure --enable-static --disable-shared\
    --without-pic --with-gnu-ld\
    --prefix="$COSMOS"\
    --sysconfdir=/zip --datarootdir=/zip/share --exec-prefix=/zip/$ARCH\
    CFLAGS="-Os"

# run make and/or make install
make -s -j2
make install -s -j2

echo "DONE."
