#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR
FOLDER="bash-bash-5.2"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd bash*/
    make V=0 -s -i clean || true
    make V=0 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd bash*/
cp $COSMOS/common.cache ./config.cache
./configure --cache-file=config.cache --prefix="$COSMOS"\
    --without-bash-malloc --enable-static-link\
    --disable-rpath --with-installed-readline\
    --disable-nls --enable-threads=posix\
    --datarootdir=/zip/share\
    --with-gnu-ld --with-curses\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
