#!/usr/bin/env bash
set -e

export COSMOPOLITAN_DISABLE_ZIPOS=0

cd $COSMO
make MODE="$MODE" V=0 -s -j$MAXPROC \
    o/$MODE/examples/greenbean.com\
    o/$MODE/examples/life.com\
    o/$MODE/examples/nesemu1.com\
    o/$MODE/examples/script.com\
    o/$MODE/examples/ttyinfo.com\
    o/$MODE/examples/unbourne.com\
    o/$MODE/examples/wall.com\
    o/$MODE/third_party/awk/awk.com\
    o/$MODE/third_party/ctags/ctags.com\
    o/$MODE/third_party/lua/lua.com\
    o/$MODE/third_party/make/make.com\
    o/$MODE/third_party/quickjs/qjs.com\
    o/$MODE/third_party/sqlite3/sqlite3.com\
    o/$MODE/third_party/tidy/tidy.com\
    o/$MODE/third_party/tree/tree.com\
    o/$MODE/tool/build/assimilate.com\
    o/$MODE/tool/build/pledge.com\
    o/$MODE/tool/build/verynice.com\
    o/$MODE/tool/net/redbean.com\
    o/$MODE/tool/viz/printimage.com

cp o/$MODE/examples/greenbean.com.dbg $COSMOS/bin/greenbean
cp o/$MODE/examples/life.com.dbg $COSMOS/bin/life
cp o/$MODE/examples/nesemu1.com.dbg $COSMOS/bin/nesemu1
cp o/$MODE/examples/script.com.dbg $COSMOS/bin/script
cp o/$MODE/examples/ttyinfo.com.dbg $COSMOS/bin/ttyinfo
cp o/$MODE/examples/unbourne.com.dbg $COSMOS/bin/unbourne
cp o/$MODE/examples/wall.com.dbg $COSMOS/bin/wall
cp o/$MODE/third_party/awk/awk.com.dbg $COSMOS/bin/awk
cp o/$MODE/third_party/ctags/ctags.com.dbg $COSMOS/bin/ctags
cp o/$MODE/third_party/lua/lua.com.dbg $COSMOS/bin/lua
cp o/$MODE/third_party/make/make.com.dbg $COSMOS/bin/make
cp o/$MODE/third_party/quickjs/qjs.com.dbg $COSMOS/bin/qjs
cp o/$MODE/third_party/sqlite3/sqlite3.com.dbg $COSMOS/bin/sqlite3
cp o/$MODE/third_party/tidy/tidy.com.dbg $COSMOS/bin/tidy
cp o/$MODE/third_party/tree/tree.com.dbg $COSMOS/bin/tree
cp o/$MODE/tool/build/assimilate.com.dbg $COSMOS/bin/assimilate
cp o/$MODE/tool/build/pledge.com.dbg $COSMOS/bin/pledge
cp o/$MODE/tool/build/verynice.com.dbg $COSMOS/bin/verynice
cp o/$MODE/tool/net/redbean.com.dbg $COSMOS/bin/redbean
cp o/$MODE/tool/viz/printimage.com.dbg $COSMOS/bin/printimage
