#!/usr/bin/env bash
set -e
shopt -s expand_aliases

alias strip=$STRIP
alias ar=$AR

../../bash*/configure --prefix="$COSMOS"\
    --without-bash-malloc --enable-static-link\
    --disable-rpath --with-installed-readline\
    --disable-nls --enable-threads=posix\
    --datarootdir=/zip/usr/share\
    --with-gnu-ld --with-curses\
    CFLAGS="-Os -I$COSMOS/include/ncurses"
