#!/bin/sh
set -e

alias strip="$STRIP"
alias ar="$AR"

"$BASELOC"/o/cli/bash/bash*/configure --prefix="$COSMOS"\
    --without-bash-malloc --enable-static-link\
    --disable-rpath --with-installed-readline\
    --disable-nls --enable-threads=posix\
    --with-gnu-ld --with-curses\
    CFLAGS="-Os -I$COSMOS/include/ncurses"
