#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.xz ]]; then
    # we already downloaded it
    cd findutils*/
    make V=0 -s -i clean || true
    make V=0 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/findutils/findutils-4.9.0.tar.xz -O sources.tar.xz
    tar -xf sources.tar.xz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd findutils*/
cp ../saved_config.cache ./config.cache
./configure --cache-file=config.cache --prefix="$COSMOS"\
    --disable-silent-rules --disable-dependency-tracking\
    --disable-asserts --disable-compiler-warnings\
    --disable-nls --disable-rpath\
    --without-selinux --with-gnu-ld=yes\
    --without-libiconv-prefix --with-packager='cosmo'\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
