#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

# download the source code
wget https://github.com/google/brotli/archive/refs/tags/v1.0.9.tar.gz -O sources.tar.gz
tar -xzf sources.tar.gz

# apply patches if any
# patch -p0 -i

# go into the source folder, configure
cd brotli*/
./configure --enable-static --disable-shared\
    --without-pic --with-gnu-ld\
    --prefix="$COSMOS"\
    CFLAGS="-Os"

# run make and/or make install
make -i -j2
make install -i -j2

echo "DONE."
