#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [ -f "sources.tar.gz" ]; then
    # we already downloaded it
    cd tree*
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://github.com/Old-Man-Programmer/tree/archive/refs/tags/2.1.1.tar.gz -O sources.tar.gz
    tar -xf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi


# go into the source folder, configure
cd tree*

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
