#!/usr/bin/env bash
set -e

echo "Initial Setup"
export BASELOC=$PWD
export COSMO=$BASELOC/cosmopolitan
export COSMOS=$BASELOC/cosmos
export RESULTS=$BASELOC/bin

mkdir -p $COSMOS
cd $COSMOS
mkdir -p include bin lib libexec share
cd $BASELOC

echo "Setting up cosmocc"

export CC=$COSMO/tool/scripts/cosmocc
export CXX=$COSMO/tool/scripts/cosmoc++
export LD=$COSMO/tool/scripts/cosmoc++
export AR=$COSMO/o/third_party/gcc/bin/x86_64-linux-musl-ar
export OBJCOPY=$COSMO/o/third_party/gcc/bin/x86_64-linux-musl-objcopy
export ZIPCOPY=$COSMO/o/tool/build/zipcopy.com

cd $BASELOC
$CC sample.c -o sample.com
./sample.com

echo "Setting up libz and libzstd in $COSMOS"
cd $COSMOS

cp $COSMO/o/third_party/zlib/zlib.a ./lib/libz.a
$AR rc ./lib/libz.a $COSMO/o/third_party/zlib/gz/*.o
echo '#include "third_party/zlib/zlib.h"' >> ./include/zlib.h

cp $COSMO/o/third_party/zstd/zstd.a ./lib/libzstd.a
echo '#include "third_party/zstd/zstd.h"' >> ./include/zstd.h

cp $COSMO/o/third_party/bzip2/bzip2.a ./lib/libbz2.a
echo '#include "third_party/bzip2/bzip2.h"' >> ./include/bzlib.h

cp $COSMO/o/third_party/sqlite3/libsqlite3.a ./lib/libsqlite3.a
echo '#include "third_party/sqlite3/sqlite3.h"' >> ./include/sqlite3.h

echo "building other packages"
cd $BASELOC

# order of PKGS matters
# brotli is crashing, so we disable it for now
PKGS=("ncurses-6.4" "readline-8.2" "openssl-1.1.1u" "gdbm-1.23" "libuuid-1.0.3" "libyaml-0.2.5" "xz-5.4.3" "wget-1.21" "cpy311-datasette")

for PKG in ${PKGS[@]}; do
    cd "./$PKG"
    chmod +x ./superconfigure
    ./superconfigure
    cd $BASELOC
done

echo "creating actually portable executables"

dbgcopy () {
    FILE="$1"
    f="$(basename -- $FILE)"
    cp "$FILE" "$RESULTS/$f.com.dbg"
}

mkdir -p $RESULTS
dbgcopy $COSMOS/bin/wget
dbgcopy $BASELOC/cpy311-datasette/datasette/datasette

cd $RESULTS
for FILE in $(ls ./*.com.dbg); do
   APE="${FILE%.*}"
   $OBJCOPY -SO binary "$FILE" "$APE"
   $ZIPCOPY "$FILE" "$APE"
done

cp $BASELOC/cpy311-datasette/datasette/datasette.com $RESULTS

echo "attempting to copy wget certs"
cd $BASELOC

mkdir -p ./usr/share/ssl/root
ls -al /etc/ssl/certs/
cp /etc/ssl/certs/*.0 ./usr/share/ssl/root
zip -qr $RESULTS/wget.com usr/share/ssl/root

# FINISH

echo "zip file with actually portable executables"
cd $BASELOC
ZFILE=results.zip
find ./bin -maxdepth 1 -name '*.com' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"

echo "second zip file with dbg"
cd $BASELOC
ZFILE=results-dbg.zip
find ./bin -maxdepth 1 -name '*.com*' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"

echo "DONE."
cd $BASELOC
ls -al results*.zip
