#!/bin/sh
set -eu

if [ -z "${GITHUB_ACTIONS:-}" ]; then 
    # we are not on GA
    if [ $(nproc) -gt 2 ]; then
        numproc=4
    else
        numproc=1
    fi
else 
    # we are on GA
    numproc=2
fi
export MAXPROC="${MAXPROC:-$numproc}"

TARGET="${1:-ERROR}"
COLLECTION="${COLLECTION:-no}"
if [ "$TARGET" = "ERROR" ]; then
    echo "build target missing!"
    exit 1
fi
TARGET="$(echo $TARGET | sed 's:/*$::')"

if [ "x$COLLECTION" = "xyes" ]; then
    echo "should build $TARGET"
    make -j$numproc $TARGET
else
    if [ -f "$TARGET/BUILD.mk" -a -f "$TARGET/check.signature" ]; then
        echo "should build o/$TARGET/built.fat"
        make LOG=stdout -j$numproc o/$TARGET/built.fat
    fi
fi
