#!/usr/bin/env bash

if [ -z "${GITHUB_ACTIONS}" ]; then 
    # we are not on GA
    if [[ $(nproc) -gt 2 ]]; then
        numproc=4
    else
        numproc=1
    fi
else 
    # we are on GA
    numproc=2
fi
export MAXPROC="${MAXPROC:-$numproc}"
echo "maxproc is $MAXPROC"

COLLECTION="${1:-$COLLECTION}"
if [[ "$COLLECTION" = "" ]]; then
    echo "did not specify collection"
    exit 1
fi

make -j"$MAXPROC" "$COLLECTION"
