#!/usr/bin/env bash
set -eux

export MODE=
export MODE_AARCH64=aarch64
export BASELOC=$(realpath $PWD)
export COSMO=$BASELOC/cosmopolitan
export COSMOS_X86=$BASELOC/cosmos/x86_64
export COSMOS_AARCH64=$BASELOC/cosmos/aarch64
export CONFIGDIR=$BASELOC/dummy
export RESULTS=$BASELOC/bin

APELINK=$COSMO/o//tool/build/apelink.com
APELINKFLAGS=

apelinkpls () {
    OUTPUT="$1"
    OUTPUT_X86_64="$2"
    OUTPUT_AARCH64="$3"
    "$APELINK" -l "$COSMO/o/$MODE/ape/ape.elf" \
        -l "$COSMO/o/$MODE_AARCH64/ape/ape.elf" \
        -M "$COSMO/ape/ape-m1.c" \
        -o "$OUTPUT" \
        "$OUTPUT_X86_64" \
        "$OUTPUT_AARCH64"
}

echo "creating fat APEs"
mkdir -p "$CONFIGDIR"
mkdir -p "$RESULTS"

# wget
apelinkpls $RESULTS/wget.com $COSMOS_X86/bin/wget $COSMOS_AARCH64/bin/wget
cd $CONFIGDIR
cp $BASELOC/wget*/wgetrc ./
mkdir -p ./usr/share/ssl/root
cp /etc/ssl/certs/*.0 ./usr/share/ssl/root/
zip $RESULTS/wget.com wgetrc
zip -qr $RESULTS/wget.com usr/
cd "$BASELOC"
rm -rf "$CONFIGDIR"
mkdir -p "$CONFIGDIR"

# datasette
apelinkpls $RESULTS/datasette.com $COSMOS_X86/bin/datasette $COSMOS_AARCH64/bin/datasette
cd $CONFIGDIR
unzip -q $BASELOC/cpy311-datasette/datasette/datasette.com || true
zip -qr $RESULTS/datasette.com Lib/
zip -qr $RESULTS/datasette.com build/
cd "$BASELOC"
rm -rf "$CONFIGDIR"
mkdir -p "$CONFIGDIR"


# pypack1
apelinkpls $RESULTS/python.com $COSMOS_X86/bin/python $COSMOS_AARCH64/bin/python
cd $CONFIGDIR
unzip -q $BASELOC/cpy311-pypack1/pypack1/python.com || true
zip -qr $RESULTS/python.com Lib/
zip -qr $RESULTS/python.com build/
cd "$BASELOC"
rm -rf "$CONFIGDIR"
mkdir -p "$CONFIGDIR"


# done?
ls -al $RESULTS

# zip them up

echo "zip file with actually portable executables"
cd $BASELOC
ZFILE=results.zip
find ./bin -maxdepth 1 -name '*.com' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"
