#!/usr/bin/env bash
set -eux

echo "Initial Setup"
export BASELOC=$PWD
ARCH="${ARCH:-x86_64}"
export COSMO="${COSMO:-$BASELOC/cosmopolitan}"
export COSMOS="${COSMOS:-$BASELOC/cosmos/$ARCH}"

if [ -z ${GITHUB_ACTIONS+x} ]; then 
    # we are not on GA
    if [[ `nproc` -gt 2 ]]; then
        numproc=$((`nproc` - 2))
    else
        numproc=1
    fi
else 
    # we are on GA
    numproc=2
fi

MAXPROC="${MAXPROC:-$numproc}"

echo "updating compiler binaries"
cd $COSMO
mkdir -p cosmocc
cd cosmocc

if [[ -f x86_64-gcc.zip ]]; then
    echo "you already downloaded x86_64-gcc.zip"
else
    wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.23/x86_64-gcc.zip
fi
if [[ -f aarch64-gcc.zip ]]; then
    echo "you already downloaded aarch64-gcc.zip"
else
    wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.23/aarch64-gcc.zip
fi

unzip -qo x86_64-gcc.zip
unzip -qo aarch64-gcc.zip

cd $COSMO
bash tool/cosmocc/package.sh

cd $BASELOC

echo "Compiling Cosmopolitan Libc"

cd $COSMO
export MODE=""
make -s -j$MAXPROC V=0 MODE="" toolchain\
    o//third_party/zlib o//third_party/zlib/gz o//third_party/zstd\
    o//third_party/sqlite3 o//third_party/sqlite3/libsqlite3.a\
    o//third_party/bzip2\
    o//tool/build/zipcopy.com o//tool/build/apelink.com

cd $COSMO
export MODE="aarch64"
make -s -j$MAXPROC V=0 MODE="aarch64" toolchain\
    o/aarch64/third_party/zlib o/aarch64/third_party/zlib/gz o/aarch64/third_party/zstd\
    o/aarch64/third_party/sqlite3 o/aarch64/third_party/sqlite3/libsqlite3.a\
    o/aarch64/third_party/bzip2

#

echo "copying third_party headers"

cd $COSMO/cosmocc/include/third_party
SUBFOLDERS='
zlib
zstd
sqlite3
bzip2
'
for SUBFOLDER in $SUBFOLDERS; do
    mkdir -p $SUBFOLDER
    cp $COSMO/third_party/$SUBFOLDER/*.h ./$SUBFOLDER || true
    cp $COSMO/third_party/$SUBFOLDER/*.inc ./$SUBFOLDER || true
done
