#!/usr/bin/env bash
set -eux

echo "Initial Setup"
export BASELOC=$PWD
ARCH="${ARCH:-x86_64}"
export COSMO="${COSMO:-$BASELOC/cosmopolitan}"
export COSMOS="${COSMOS:-$BASELOC/cosmos/$ARCH}"

if [ -z ${GITHUB_ACTIONS+x} ]; then 
    # we are not on GA
    if [[ `nproc` -gt 2 ]]; then
        numproc=$((`nproc` - 2))
    else
        numproc=1
    fi
else 
    # we are on GA
    numproc=2
fi

MAXPROC="${MAXPROC:-$numproc}"

echo "updating compiler binaries"
cd $COSMO/tool/cosmocc
wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.18/x86_64-gcc.zip
unzip -o x86_64-gcc.zip
wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.18/aarch64-gcc.zip
unzip -o aarch64-gcc.zip

echo "Compiling Cosmopolitan Libc"
cd $BASELOC

cd $COSMO
export MODE=""
make -s -j$MAXPROC V=0 MODE="" toolchain\
    o//third_party/zlib o//third_party/zlib/gz o//third_party/zstd\
    o//third_party/sqlite3 o//third_party/sqlite3/libsqlite3.a\
    o//third_party/bzip2\
    o//tool/build/zipcopy.com o//tool/build/apelink.com
$COSMO/tool/cosmocc/bin/x86_64-unknown-cosmo-cc --update

cd $COSMO
export MODE="aarch64"
make -s -j$MAXPROC V=0 MODE="aarch64" toolchain\
    o/aarch64/third_party/zlib o/aarch64/third_party/zlib/gz o/aarch64/third_party/zstd\
    o/aarch64/third_party/sqlite3 o/aarch64/third_party/sqlite3/libsqlite3.a\
    o/aarch64/third_party/bzip2
$COSMO/tool/cosmocc/bin/aarch64-unknown-cosmo-cc --update
