#!/usr/bin/env bash
set -eux

echo "Initial Setup"
export BASELOC=$PWD
export COSMO=$BASELOC/cosmopolitan
export RESULTS=$BASELOC/bin

echo "Compiling Cosmopolitan Libc"
cd $BASELOC

cd $COSMO
export MODE=""
make -s -j2 V=0 MODE="" toolchain\
    o//third_party/zlib o//third_party/zlib/gz o//third_party/zstd\
    o//third_party/sqlite3 o//third_party/sqlite3/libsqlite3.a\
    o//third_party/bzip2\
    o//tool/build/zipcopy.com o//tool/build/apelink.com
$COSMO/bin/x86_64-unknown-cosmo-cc --update

cd $COSMO
export MODE="aarch64"
make -s -j2 V=0 MODE="aarch64" toolchain\
    o/aarch64/third_party/zlib o/aarch64/third_party/zlib/gz o/aarch64/third_party/zstd\
    o/aarch64/third_party/sqlite3 o/aarch64/third_party/sqlite3/libsqlite3.a\
    o/aarch64/third_party/bzip2
$COSMO/bin/aarch64-unknown-cosmo-cc --update
