#!/usr/bin/env bash
set -eux

make ARCH=x86_64 datasette
make clean
make ARCH=aarch64 datasette

export MODE=
export MODE_AARCH64=aarch64
export BASELOC=$(realpath $PWD)
export COSMO=$BASELOC/cosmopolitan
export COSMOS_X86=$BASELOC/cosmos/x86_64
export COSMOS_AARCH64=$BASELOC/cosmos/aarch64
export CONFIGDIR=$BASELOC/dummy
export RESULTS=$BASELOC/bin

APELINK=$COSMO/o//tool/build/apelink.com
APELINKFLAGS=

apelinkpls () {
    OUTPUT="$1"
    OUTPUT_X86_64="$2"
    OUTPUT_AARCH64="$3"
    "$APELINK" -l "$COSMO/o/$MODE/ape/ape.elf" \
        -l "$COSMO/o/$MODE_AARCH64/ape/ape.elf" \
        -M "$COSMO/ape/ape-m1.c" \
        -o "$OUTPUT" \
        "$OUTPUT_X86_64" \
        "$OUTPUT_AARCH64"
}

echo "creating fat APEs"
mkdir -p "$CONFIGDIR"
mkdir -p "$RESULTS"

# datasette
apelinkpls $RESULTS/datasette.com $COSMOS_X86/bin/datasette $COSMOS_AARCH64/bin/datasette
cp $COSMOS_X86/bin/datasette $RESULTS/datasette.x86_64 
cp $COSMOS_AARCH64/bin/datasette $RESULTS/datasette.aarch64
cd $CONFIGDIR
unzip -q $BASELOC/cpy311-datasette/datasette/datasette.com || true
cp -r $BASELOC/cpy311-datasette/datasette/dummy/lib* ./build
ls -al build/
zip -qr $RESULTS/datasette.com Lib/
zip -qr $RESULTS/datasette.com build/
cd "$BASELOC"
rm -rf "$CONFIGDIR"
mkdir -p "$CONFIGDIR"

# done?
ls -al $RESULTS

# zip them up
echo "zip file with actually portable executables"
cd $BASELOC
ZFILE="${ZFILENAME:-py-datasette}.zip"
find ./bin -maxdepth 1 -name '*.com' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"

ZFILE="${ZFILENAME:-py-datasette}-dbg.zip"
find ./bin -maxdepth 1 -name '*' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"
