#!/usr/bin/env bash
set -eux

make ARCH=x86_64 editor
make clean
make ARCH=aarch64 editor

export MODE=
export MODE_AARCH64=aarch64
export BASELOC=$(realpath $PWD)
export COSMO=$BASELOC/cosmopolitan
export COSMOS_X86=$BASELOC/cosmos/x86_64
export COSMOS_AARCH64=$BASELOC/cosmos/aarch64
export CONFIGDIR=$BASELOC/dummy
export RESULTS=$BASELOC/bin

APELINK=$COSMO/o//tool/build/apelink.com
APELINKFLAGS=

apelinkpls () {
    OUTPUT="$1"
    OUTPUT_X86_64="$2"
    OUTPUT_AARCH64="$3"
    "$APELINK" -l "$COSMO/o/$MODE/ape/ape.elf" \
        -l "$COSMO/o/$MODE_AARCH64/ape/ape.elf" \
        -M "$COSMO/ape/ape-m1.c" \
        -o "$OUTPUT" \
        "$OUTPUT_X86_64" \
        "$OUTPUT_AARCH64"
}

echo "creating fat APEs"
mkdir -p "$CONFIGDIR"
mkdir -p "$RESULTS"

# the zip folder
sudo rm -f /zip
sudo ln -sf "$CONFIGDIR" /zip
cd /zip
mkdir -p share
cp -r $COSMOS_X86/x86_64 ./
cp -r $COSMOS_AARCH64/aarch64 ./
cp -r $COSMOS_X86/share/terminfo ./share
cp -r $COSMOS_X86/share/vim ./share
cp -r $COSMOS_X86/share/emacs ./share
ls -al /zip


cd $BASELOC
ls -al ./

# emacs
cd "$BASELOC"
apelinkpls $RESULTS/emacs.com $COSMOS_X86/bin/emacs $COSMOS_AARCH64/bin/emacs
cd /zip
zip -r $RESULTS/emacs.com \
    share/terminfo \
    $(find x86_64 -type f | grep 'emacs\.pdmp') \
    $(find aarch64 -type f | grep 'emacs\.pdmp') \
    $(find share/emacs -type f |
    grep -v '\.el.gz$' |
    grep -v refcards |
    grep -v images)

# vim
cd "$BASELOC"
apelinkpls $RESULTS/vim.com $COSMOS_X86/bin/vim $COSMOS_AARCH64/bin/vim
cd /zip
zip -r $RESULTS/vim.com \
    share/terminfo \
    share/vim


# zip them up
echo "zip file with actually portable executables"
cd $BASELOC
ZFILE="${ZFILENAME:-editor}.zip"
find ./bin -maxdepth 1 -name '*.com' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"

ZFILE="${ZFILENAME:-editor}-dbg.zip"
find ./bin -maxdepth 1 -name '*' -print0 | tee /dev/tty | xargs -0 zip "$ZFILE"
