#!/usr/bin/env bash

# update?
sudo apt update

# ssl certs
sudo apt-get install -y ca-certificates libssl-dev\
    qemu qemu-utils qemu-user-static\
    texinfo groff\
    cmake ninja-build bison zip\
    pkg-config build-essential autoconf re2c

# the zip folder
sudo mkdir -p /zip
sudo chmod -R 0777 /zip

# the actual build folder
sudo mkdir -p /ahgamut
sudo chmod -R 0777 /ahgamut

cd "$GITHUB_WORKSPACE" || exit
cd ../
cp -r superconfigure /ahgamut
cd /ahgamut/superconfigure || exit

# cosmo
git clone https://github.com/ahgamut/cosmopolitan --depth=1 --branch=superconf cosmopolitan

sudo cp cosmopolitan/build/bootstrap/ape.elf /usr/bin/ape
sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

ls /proc/sys/fs/binfmt_misc/
