#!/usr/bin/env bash

# update?
sudo apt update

# ssl certs
sudo apt-get install -y ca-certificates libssl-dev\
    qemu-user-static\
    texinfo groff libtool\
    cmake ninja-build bison flex zip lzip\
    pkg-config build-essential autoconf re2c

# github workspace can be the build folder,
# now that /zip stuff is not needed to run
cd "$GITHUB_WORKSPACE" || exit

# cosmo
git clone https://github.com/jart/cosmopolitan --depth=1

sudo cp cosmopolitan/build/bootstrap/ape.elf /usr/bin/ape
sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

ls /proc/sys/fs/binfmt_misc/
