#!/usr/bin/env bash

# update?
sudo apt update

# ssl certs
sudo apt-get install -y ca-certificates libssl-dev
sudo apt-get install -y qemu qemu-utils qemu-user-static
sudo apt-get install -y texinfo
sudo apt-get install -y cmake ninja-build

# the zip folder
sudo mkdir -p /zip
sudo chmod -R 0777 /zip

# cosmo
git clone https://github.com/ahgamut/cosmopolitan --depth=1 --branch=superconf cosmopolitan

sudo cp cosmopolitan/build/bootstrap/ape.elf /usr/bin/ape
sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

ls /proc/sys/fs/binfmt_misc/
