#!/bin/sh
set -e

export COMPATINCLUDEDIR="$COSMOS/include/gdbm"
"$BASELOC"/o/lib/gdbm/gdbm*/configure --prefix="$COSMOS"\
    --disable-memory-mapped-io --enable-libgdbm-compat\
    --disable-shared --enable-static\
    --disable-nls --disable-rpath\
    --without-pic --with-gnu-ld --without-readline\
    --sysconfdir="$COSMOS/share" --datarootdir="$COSMOS/share"\
    CFLAGS="-Os"
