#!/usr/bin/env bash
set -eux

cd $BASELOC

# create the COSMOS and related folders
mkdir -p $COSMOS
mkdir -p $DIRCONFIG
mkdir -p $RESULTS/bin
sudo rm -f /zip
sudo ln -sf $COSMOS /zip
cd $COSMOS
mkdir -p include bin lib libexec share $ARCH
cd $BASELOC

echo "Setting up cosmocc"
cd $BASELOC
rm -f sample.com sample.com.dbg
$CC sample.c -o sample.com
./sample.com

echo "Setting up libz and libzstd in $COSMOS"
mv $COSMO/cosmocc/$ARCH-linux/cosmo/lib/*.a $COSMOS/lib || true # running many times
cd $COSMOS
ls $COSMOS/lib
# 
cp ./lib/libpthread.a ./lib/libcrypt.a
cp ./lib/libpthread.a ./lib/libatomic.a
cp ./lib/libpthread.a ./lib/libncursesw.a
cp ./lib/libpthread.a ./lib/libgio-2.0.a
cp ./lib/libpthread.a ./lib/libgobject-2.0.a
cp ./lib/libpthread.a ./lib/libglib-2.0.a

if [ -f ./include/zlib.h ]; then
    echo "already have zlib.h"
else
    echo '#include "third_party/zlib/zlib.h"' >> ./include/zlib.h
fi

if [ -f ./lib/libz.a ]; then
    echo "already have libz.a"
else
    cp $COSMO/o/$MODE/third_party/zlib/zlib.a ./lib/libz.a
    $AR rcu ./lib/libz.a $COSMO/o/$MODE/third_party/zlib/gz/*.o
fi

cp $COSMO/o/$MODE/third_party/zstd/zstd.a ./lib/libzstd.a
echo '#include "third_party/zstd/zstd.h"' >> ./include/zstd.h

cp $COSMO/o/$MODE/third_party/bzip2/bzip2.a ./lib/libbz2.a
echo '#include "third_party/bzip2/bzlib.h"' >> ./include/bzlib.h

cp $COSMO/o/$MODE/third_party/sqlite3/libsqlite3.a ./lib/libsqlite3.a
echo '#include "third_party/sqlite3/sqlite3.h"' >> ./include/sqlite3.h

# ls $COSMOS/lib -al
# ls $COSMOS/include -al
