#!/usr/bin/env bash
set -eux

cd $BASELOC

# create the COSMOS and related folders
mkdir -p $COSMOS
mkdir -p $DIRCONFIG
mkdir -p $RESULTS/bin
cd $COSMOS
mkdir -p include bin lib libexec share $ARCH
mkdir -p /zip/usr/share /zip/$ARCH
cd $BASELOC

# add basic config.cache for configure scripts
cp $BASELOC/vars/common.cache $COSMOS

echo "Setting up cosmocc"
cd $BASELOC
rm -f sample.com sample.com.dbg
$CC sample.c -o sample.com
./sample.com

# don't copy core cosmo libs into $COSMOS, because
# cosmocc adds them via -L anyway
# cp $COSMO/cosmocc/$ARCH-linux-cosmo/lib/*.a $COSMOS/lib || true

echo "Setting up libz and libzstd in $COSMOS"
cd $COSMOS

for lib in crypt atomic ncursesw gio-2.0 gobject-2.0 glib-2.0; do
    printf '\041\074\141\162\143\150\076\012' >"./lib/lib$lib.a"
done

if [ -f ./include/zlib.h ]; then
    echo "already have zlib.h"
else
    echo '#include "third_party/zlib/zlib.h"' >> ./include/zlib.h
fi

if [ -f ./lib/libz.a ]; then
    echo "already have libz.a"
else
    cp $COSMO/o/$MODE/third_party/zlib/zlib.a ./lib/libz.a
    $AR rcu ./lib/libz.a $COSMO/o/$MODE/third_party/zlib/gz/*.o
fi

cp $COSMO/o/$MODE/third_party/zstd/zstd.a ./lib/libzstd.a
echo '#include "third_party/zstd/zstd.h"' >> ./include/zstd.h

cp $COSMO/o/$MODE/third_party/bzip2/bzip2.a ./lib/libbz2.a
echo '#include "third_party/bzip2/bzlib.h"' >> ./include/bzlib.h

cp $COSMO/o/$MODE/third_party/sqlite3/libsqlite3.a ./lib/libsqlite3.a
echo '#include "third_party/sqlite3/sqlite3.h"' >> ./include/sqlite3.h

# ls $COSMOS/lib -al
# ls $COSMOS/include -al

ls $COSMOS/lib
