#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

# download the source code
# wget
# tar

# apply patches if any
# patch -p0 -i

# go into the source folder, configure

# run make and/or make install

echo "DONE."
