#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd openssl*
    make -s -i clean
    cd ..
else
    # download the source code
    wget -q https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1u.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # OpenSSL 1.1.1u
    #
    # have to change two lines in crypto/rand/rand_unix.c, to
    #
    # - force an ifdef enabling use of getrandom
    # - use the getrandom() function instead of the syscall
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd openssl*
ARCH="${ARCH:-x86_64}"
./Configure no-shared no-asm\
    no-dso no-dynamic-engine no-engine no-pic\
    no-autoalginit no-autoerrinit\
    --with-rand-seed=getrandom\
    CFLAGS="-Os"\
    --prefix=$COSMOS linux-$ARCH

# run make and/or make install
make -s -j
make install_sw -s -j

echo "DONE."
