#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

ARCH="${ARCH:-x86_64}"
cd $COSMO/o/third_party/gcc
if [[ -f "$ARCH-gcc.zip" ]]; then
    # we already downloaded it
    cd $BASELOC
else
    wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.15/$ARCH-gcc.zip
    unzip $ARCH-gcc.zip
    rm -f bin/$ARCH-*musl-gcc
fi

echo "DONE."
