#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

ARCH="${ARCH:-x86_64}"
cd $COSMO/o/third_party/gcc
if [[ -f "x86_64-gcc.zip" ]]; then
    # we already downloaded it
    cd $BASELOC
else
    wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.15/x86_64-gcc.zip
    unzip -o x86_64-gcc.zip
    wget -q https://github.com/ahgamut/superconfigure/releases/download/z0.0.15/aarch64-gcc.zip
    unzip -o aarch64-gcc.zip
    cd $BASELOC
fi

echo "DONE."
