#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="libuuid*"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd expat*
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i ./minimal.diff
fi

# go into the source folder, configure
cd expat*
./configure --enable-static --disable-shared\
    --without-pic --with-gnu-ld\
    --disable-tests --disable-examples --without-docbook\
    --with-getrandom\
    --prefix="$COSMOS" --sysconfdir=/zip/etc --datarootdir=/zip/share \
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
