#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd ninja*
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://github.com/ninja-build/ninja/archive/refs/tags/v1.11.1.tar.gz -O sources.tar.gz
    tar -xf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd ninja*
cmake -G Ninja ..\
    -DCMAKE_BUILD_SHARED=OFF\
    -DCMAKE_BUILD_STATIC=ON\
    -DCMAKE_INSTALL_PREFIX="$COSMOS"

# run make and/or make install
ninja -j$MAXPROC
ninja install -j$MAXPROC

echo "DONE."
