#!/bin/sh
set -e

ARCH="${ARCH:-x86_64}"
alias strip="$STRIP"
alias ar="$AR"

export GOBJECT_LIBS=""

"$BASELOC"/o/lib/gnutls/gnutls*/configure --sysconfdir=/zip --datarootdir=/zip/usr/share\
    --libexecdir=/zip/"$ARCH" --prefix="$COSMOS"\
    --disable-shared --enable-static\
    --with-gnu-ld --disable-cxx\
    --disable-nls --disable-rpath --disable-tests\
    --disable-hardware-acceleration --disable-padlock\
    --disable-libdane --disable-guile\
    --disable-bash-tests --disable-doc\
    --without-p11-kit --without-tpm --without-tpm2\
    --with-included-libtasn1 --with-included-unistring\
    --enable-fat --without-zstd\
    --with-default-trust-store-file=/zip/usr/share/ssl/certs/ca-certificates.crt \
    --with-default-trust-store-dir=/zip/usr/share/ssl/certs \
    --with-default-trust-store-dir=/zip/usr/share/ssl/default.crl \
    --with-unbound-root-key-file=/zip/usr/share/unbound/root.key \
    CFLAGS="-Os"
