#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd git*/
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://github.com/git/git/archive/refs/tags/v2.42.0.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd git*/
autoconf || true

export CURL_LDFLAGS="-lcurl -lbrotlidec -lbrotlienc -lbrotlicommon -lssh2 -lzstd -lssl -lcrypto -lz"
export CSPRNG_METHOD="getrandom"
export NO_PERL=1
export NO_POLL=1
export NO_PYTHON=1
export SHELL_PATH="sh"

./configure --prefix="$COSMOS"\
    --with-curl --with-openssl --enable-pthreads="-lpthread"\
    --without-tcltk --without-python \
    --sysconfdir=/zip/etc --datarootdir=/zip/share\
    --with-pager=less --with-editor=vim  --with-shell=sh\
    --with-gitconfig=/zip/gitconfig --with-gitattributes=/zip/gitattributes\
    --with-sane-tool-path=""\
   CFLAGS="-Os" LDFLAGS="-L$COSMOS/lib" LIBS="-lcurl -lbrotlidec -lbrotlienc -lbrotlicommon -lssh2 -lzstd -lssl -lcrypto -lz"
 
# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
