#!/usr/bin/env bash
set -e

TARGET_ARCH="${TARGET_ARCH:-x86_64}"

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [ -f "sources.tar.gz" ]; then
    # we already downloaded it
    rm -rf build
    mkdir -p build
else
    # download the source code
    wget -q https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-15.0.7.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
    mkdir -p build
fi

SYSROOT_BUILD=$(realpath ./build)

# go into the source folder, configure
cd build

cmake -S ../llvm-project*/llvm -B ./ -G Ninja \
    -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX"\
    -DCMAKE_INSTALL_PREFIX="$COSMOS"\
    -DCLANG_TOOL_APINOTES_TEST_BUILD=OFF\
    -DCLANG_TOOL_ARCMT_TEST_BUILD=OFF\
    -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD=OFF\
    -DCLANG_TOOL_C_ARCMT_TEST_BUILD=OFF\
    -DCLANG_TOOL_C_INDEX_TEST_BUILD=OFF\
    -DCMAKE_INSTALL_OLDINCLUDEDIR="$COSMOS/include"\
    -DBacktrace_INCLUDE_DIR="$COSMOS/include" \
    -DC_INCLUDE_DIRS="$COSMOS/include" \
    -DZLIB_INCLUDE_DIR="$COSMOS/include" \
    -DFFI_INCLUDE_DIR="$COSMOS/include" \
    -DLLVM_INCLUDE_TESTS=OFF\
    -DCLANG_INCLUDE_TESTS=OFF\
    -DLLVM_TOOL_LLVM_C_TEST_BUILD=OFF\
    -DLLVM_ENABLE_PROJECTS="clang"\
    -DCMAKE_BUILD_TYPE=MinSizeRel\
    -DLLVM_TARGETS_TO_BUILD="X86;AArch64"\
    -DLLVM_PARALLEL_COMPILE_JOBS="$MAXPROC"\
    -DLLVM_PARALLEL_LINK_JOBS=1\
    -DLLVM_ENABLE_PIC=OFF\
    -DLLVM_ENABLE_LIBCXX=OFF\
    -DLLVM_ENABLE_LLVM_LIBC=OFF\
    -DLLVM_ENABLE_MODULES=OFF\
    -DLLVM_ENABLE_PEDANTIC=OFF\
    -DBUILD_SHARED_LIBS=OFF\
    -DLLVM_BUILD_STATIC=ON\
    -DLLVM_ENABLE_LIBFFI=OFF\
    -DLLVM_ENABLE_LIBPFM=OFF\
    -DLLVM_ENABLE_LIBEDIT=OFF\
    -DLLVM_ENABLE_TERMINFO=OFF\
    -DLLVM_ENABLE_LIBXML2=OFF\
    -DLLVM_ENABLE_CURL=OFF\
    -DLLVM_ENABLE_LIBTHREADS=ON

# run make and/or make install
ninja -j$MAXPROC -k5
cp bin/* $COSMOS/bin

echo "DONE."
