#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="readline-8.2"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make V=0 -s -i clean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # disable using pselect or FIONREAD when typing text
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd $FOLDER
cp ../saved_config.cache ./config.cache
./configure --cache-file=config.cache --disable-shared --enable-static\
    --enable-multibyte --prefix=$COSMOS\
    --with-curses\
    --sysconfdir=/zip --datarootdir=/zip/share\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
