#!/usr/bin/env bash
set -e
shopt -s expand_aliases
export COSMOPOLITAN_DISABLE_ZIPOS=1

ARCH="${ARCH:-x86_64}"

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR
FOLDER="emacs-28.2"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make V=0 -s -i distclean
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/emacs/emacs-28.2.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd $FOLDER
export GOBJECT_LIBS=""
export PKG_CONFIG=""
export LIBGNUTLS_CFLAGS="-I$COSMOS/include/gnutls -I$COSMOS/include/nettle"
export LIBGNUTLS_LIBS="-L$COSMOS/lib -lgnutls -lhogweed -lnettle -lgmp"

cp $COSMOS/common.cache ./config.cache
./configure --cache-file=config.cache --with-gnutls=ifavailable\
    --host=$ARCH-linux-gnu --with-threads\
    --without-dbus --without-selinux\
    --with-file-notification=no --without-modules\
    --sysconfdir=/zip --datarootdir=/zip/share\
    --libexecdir=/zip/$ARCH --prefix=$COSMOS\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
