#!/bin/sh
set -e

rm -rf ./pypack2
cp -r "$BASELOC"/o/python/cpy311-pypack2/pypack2 ./
cd pypack2

./configure --disable-shared --disable-loadable-sqlite-extensions\
    --with-lto=no --without-system-expat --without-system-ffi\
    --with-pymalloc --with-openssl="$COSMOS"/ssl\
    --with-tzpath=/zip/usr/share/zoneinfo\
    --sysconfdir="$COSMOS/share" --datarootdir="$COSMOS/share"\
    --prefix="$COSMOS"\
    CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses -I$COSMOS/include/uuid"

# run make and/or make install
make V=0 -s -j"$MAXPROC"
mkdir -p dummy
cp -r build/lib* ./dummy
cp ./python "$COSMOS"/bin/pypack2
