#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi


if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd tar*/
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/tar/tar-1.35.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd tar*/
./configure --prefix="$COSMOS"\
    --disable-acl --disable-nls --disable-rpath\
    --without-posix-acls --without-selinux\
    --with-packager="cosmo" --without-xattrs\
    --with-gzip=gzip --with-bzip2=bzip2\
    --with-xz=xz --with-zstd=zstd\
    --exec-prefix=/zip --datarootdir=/zip/share\
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
