#!/usr/bin/env bash

if [ -z ${GITHUB_ACTIONS+x} ]; then 
    # we are not on GA
    if [[ `nproc` -gt 2 ]]; then
        numproc=$((`nproc` - 2))
    else
        numproc=1
    fi
else 
    # we are on GA
    numproc=2
fi

export MAXPROC="${MAXPROC:-$numproc}"

export ARCH=aarch64
export MODE=aarch64
export BASELOC=$(realpath $PWD)
export COSMO=$BASELOC/cosmopolitan
export COSMOS=$BASELOC/cosmos/$ARCH
export RESULTS=$BASELOC/results
export DIRCONFIG=$BASELOC/cosmos/config

PREFIX="$COSMO/tool/cosmocc/bin/$ARCH-unknown-cosmo"
export CC=$PREFIX-cc
export CXX=$PREFIX-c++
export LD=$PREFIX-cc
export OBJCOPY=$PREFIX-objcopy
export AR=$PREFIX-ar
export STRIP=$PREFIX-strip
export ZIPCOPY=$COSMO/o/tool/build/zipcopy.com
