#!/usr/bin/env bash
set -e

export ARCH=x86_64
export MODE=
export BASELOC=$(realpath $PWD)
export COSMO=$BASELOC/cosmopolitan
export COSMOS=$BASELOC/cosmos/$ARCH
export RESULTS=$BASELOC/bin
export DIRCONFIG=$BASELOC/cosmos/config

PREFIX="$COSMO/bin/$ARCH-unknown-cosmo"
export CC=$PREFIX-cc
export CXX=$PREFIX-c++
export LD=$PREFIX-cc
export OBJCOPY=$PREFIX-objcopy
export AR=$PREFIX-ar
export STRIP=$PREFIX-strip
export ZIPCOPY=$COSMO/o/tool/build/zipcopy.com
