#!/bin/sh
set -e

export OPENSSL_CFLAGS=""
export OPENSSL_LIBS="-lssl -lcrypto"

"$BASELOC"/o/web/rsync/rsync*/configure --prefix="$COSMOS"\
    --with-rsyncd-conf="$COSMOS/share/rsyncd.conf" --with-included-popt\
    --with-openssl-conf="$COSMOS/share/openssl.conf" --without-included-zlib\
    --sysconfdir="$COSMOS/etc" --datarootdir="$COSMOS/share"\
    --disable-iconv --disable-lz4 --disable-xxhash\
    --disable-acl-support --disable-xattr-support\
    --disable-locale --disable-md2man\
    --disable-roll-simd --disable-md5-asm --disable-roll-asm\
    CFLAGS="-Os"
