#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="libuuid*"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd libssh2*
    make V=0 -s -i clean
    cd ..
else
    # download the source code
    wget -q https://github.com/libssh2/libssh2/releases/download/libssh2-1.11.0/libssh2-1.11.0.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i ./minimal.diff
fi

# go into the source folder, configure
cd libssh2*
cp $COSMOS/common.cache ./config.cache
./configure --cache-file=config.cache --enable-static --disable-shared\
    --with-crypto=openssl --with-libssl-prefix="$COSMOS/lib"\
    --without-pic --with-gnu-ld --disable-rpath\
    --disable-tests --disable-examples-build --disable-werror\
    --prefix="$COSMOS" --sysconfdir=/zip/etc --datarootdir=/zip/share\
    CFLAGS="-Os"

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
