#!/usr/bin/env bash
set -e
shopt -s expand_aliases

export STRIP="/bin/true"

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR
FOLDER="vim-9.0.1670"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i distclean
    cd ..
else
    # download the source code
    wget -q https://github.com/vim/vim/archive/refs/tags/v9.0.1670.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

cd $FOLDER
# go into the source folder, configure
./configure --disable-darwin --disable-smack --disable-selinux\
    --disable-xsmp --enable-luainterp=no --enable-perlinterp=no\
    --enable-pythoninterp=no --enable-python3interp=no\
    --enable-tclinterp=no --enable-rubyinterp=no\
    --disable-netbeans --disable-cscope --enable-multibyte\
    --disable-xim --disable-fontset --enable-gui=no\
    --disable-nls --disable-sysmouse --disable-acl\
    --disable-canberra --disable-libsodium\
    --without-x --with-tlib=tinfo\
    --with-local-dir=$COSMOS/lib\
    --sysconfdir=/zip --datarootdir=/zip/share\
    --prefix=$COSMOS\
    CFLAGS="-Os -I$COSMOS/include" LDFLAGS="-L$COSMOS/lib" 

# run make and/or make install
make -s -j
make install -s -j

echo "DONE."
