#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="pypack1"

if [ -d "$FOLDER" ]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean
    cd ..
else
    # download the source code
    git clone --depth=1 --branch=pypack1 https://github.com/ahgamut/cpython pypack1
    # tar

    # apply patches if any
    # patch -p0 -i
fi

# go into the source folder, configure
cd $FOLDER
./configure --disable-shared --disable-loadable-sqlite-extensions\
    --with-lto=no --without-system-expat --without-system-ffi\
    --with-pymalloc --with-openssl=$COSMOS/ssl\
    --with-tzpath=/zip/usr/share/zoneinfo\
    --prefix=$COSMOS --exec-prefix=$COSMOS/$ARCH\
    CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses -I$COSMOS/include/uuid"

# run make and/or make install
make -s -j2
mkdir -p dummy
cp -r build/lib* ./dummy
cp ./python $COSMOS/bin

echo "DONE."

