#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="wget-1.21"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/wget/wget-1.21.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # disable all the checks in fseeko.c, and just call cosmo's fseeko
    # remove the FALLTHROUGH macro if there is a complaint
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd $FOLDER

export OPENSSL_CFLAGS=""
export OPENSSL_LIBS="-lssl -lcrypto"

./configure --prefix="$COSMOS"\
    --with-ssl=openssl --with-openssl=yes\
    --sysconfdir=/zip --with-gnu-ld=yes\
    --enable-threads=posix --disable-rpath\
    --disable-xattr --disable-nls\
    --disable-pcre --disable-pcre2\
    CFLAGS="-Os" LIBS="-lbz2 -lz -llzma"

# run make and/or make install
make V=1 -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
