#!/bin/sh
set -e

apelinkpls () {
    OUTPUT="$1"
    OLDNAME_X86_64="$(basename -- "$2")"
    OLDNAME_AARCH64="$(basename -- "$3")"
    TARG_FOLD="$(dirname "$OUTPUT")"
    "$APELINK" -l "$COSMO/o/x86_64/ape/ape.elf" \
        -l "$COSMO/o/aarch64/ape/ape.elf" \
        -M "$COSMO/ape/ape-m1.c" \
        -o "$OUTPUT" \
        "$2" \
        "$3"
    cp "$2" "$TARG_FOLD/$OLDNAME_X86_64.x86_64"
    cp "$3" "$TARG_FOLD/$OLDNAME_AARCH64.aarch64"
}

# pypack1
apelinkpls "$RESULTS"/bin/pypack1.com "$COSMOS_X86_64"/bin/pypack1 "$COSMOS_AARCH64"/bin/pypack1
cd /zip

mkdir -p pypack1 && cd pypack1
unzip -qo "$BASELOC"/o/python/cpy311-pypack1/build/x86_64/pypack1/python.com || true

mkdir -p build
cp -r "$BASELOC"/o/python/cpy311-pypack1/build/aarch64/pypack1/dummy/lib* ./build || true
cp -r "$BASELOC"/o/python/cpy311-pypack1/build/x86_64/pypack1/dummy/lib* ./build || true
ls -al build/

zip -qr "$RESULTS"/bin/pypack1.com Lib/
zip -qr "$RESULTS"/bin/pypack1.com build/

cd /zip
zip -qr "$RESULTS"/bin/pypack1.com usr/share/terminfo usr/share/ssl
cd "$BASELOC"
rm -rf /zip/pypack1
