#!/bin/sh
set -e

alias strip="$STRIP"
alias ar="$AR"

export CURL_LDFLAGS="-lcurl -lpsl -lbrotlidec -lbrotlienc -lbrotlicommon -lssh2 -lzstd -lssl -lcrypto -lz"
export CSPRNG_METHOD="getrandom"
export NO_PERL=1
export NO_POLL=1
export NO_PYTHON=1
export SHELL_PATH="sh"
export LIBS="-lcurl -lpsl -lbrotlidec -lbrotlienc -lbrotlicommon -lssh2 -lzstd -lssl -lcrypto -lz"

cp -r "$BASELOC"/o/web/git/git*/* .

./configure --prefix="$COSMOS"\
    --with-curl --with-openssl --enable-pthreads="-lpthread"\
    --without-tcltk --without-python \
    --sysconfdir=/zip/etc --datarootdir=/zip/usr/share\
    --with-pager=less --with-editor=vim  --with-shell=sh\
    --with-gitconfig=/zip/gitconfig --with-gitattributes=/zip/gitattributes\
    --with-sane-tool-path=""\
   CFLAGS="-Os" LDFLAGS="-L$COSMOS/lib" 

make -j"$MAXPROC"
make install -j"$MAXPROC"
