#!/usr/bin/env bash
set -e

TARGET_ARCH="${TARGET_ARCH:-x86_64}"

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="gcc"

if [ -d "$FOLDER" ]; then
    # we already downloaded it
    rm -rf build
    mkdir -p build/usr/include
else
    # download the source code
    git clone --depth=1 --branch=portcosmo-11.2 https://github.com/ahgamut/gcc $FOLDER
    mkdir -p build/usr/include
    # tar

    # apply patches if any
    # patch -p0 -i
fi

SYSROOT_BUILD=$(realpath ./build)

# go into the source folder, configure
cd build
../$FOLDER/configure --prefix=$COSMOS --with-sysroot="$SYSROOT_BUILD" \
    --with-system-zlib --disable-shared --enable-static --disable-libquadmath \
    --disable-decimal-float --disable-libitm --disable-fixed-point --disable-lto \
    --with-static-standard-libraries --disable-libada --disable-libssp \
    --disable-host-shared --disable-objc-gc --enable-languages=c,c++ --disable-bootstrap \
    --disable-assembly --disable-werror --disable-multilib --enable-tls \
    --disable-libmudflap --disable-libsanitizer --disable-gnu-indirect-function \
    --disable-libmpx --enable-initfini-array --disable-libstdcxx --without-libffi \
    --without-libatomic --disable-gcov --disable-analyzer --disable-libvtv \
    --disable-libgomp --disable-libatomic \
    --with-gnu-as=yes --with-gnu-ld=yes --build=$ARCH-linux-gnu \
    --target=$TARGET_ARCH-linux-cosmo \

# run make and/or make install
make -s -j6 all-gcc
make -i -s -j6 install

echo "DONE."
