#!/bin/sh
set -e

cp -r "$BASELOC"/o/games/nethack/NetHack*/* ./

sudo mkdir -p /zip/cfg

patch -p0 --fuzz=10 -i "/home/runner/work/superconfigure/superconfigure/games/nethack/$1"

sh sys/unix/setup.sh sys/unix/hints/linux
