#!/bin/sh

export COSMOPOLITAN_DISABLE_ZIPOS=1
export ARCH=x86_64
export MODE=x86_64
export BASELOC=$(realpath "$PWD")
export COSMO=$BASELOC/cosmopolitan
export COSMOS=$BASELOC/cosmos/$ARCH
export RESULTS=$BASELOC/results
#export PKG_CONFIG_PATH=$COSMOS/lib/pkgconfig:$COSMOS/share/pkgconfig:$COSMOS/share/pkg-config
export PKG_CONFIG_LIBDIR=$COSMOS/lib/pkgconfig:$COSMOS/share/pkgconfig:$COSMOS/share/pkg-config
export ACLOCAL_PATH="$COSMOS/share/aclocal"

PREFIX0="$COSMO/cosmocc/bin/$ARCH-unknown-cosmo"
export CC=$PREFIX0-cc
export CXX=$PREFIX0-c++
PREFIX1="$COSMO/cosmocc/bin/$ARCH-linux-cosmo"
export LD=$PREFIX1-ld
export OBJCOPY=$PREFIX1-objcopy
export AR=$PREFIX1-ar
export STRIP=$PREFIX1-strip
export ZIPCOPY=$COSMO/o/tool/build/zipcopy
