#!/bin/sh

export COSMOPOLITAN_DISABLE_ZIPOS=1
export ARCH=aarch64
export MODE=aarch64
export BASELOC=$(realpath "$PWD")
export COSMO=$BASELOC/cosmopolitan
export COSMOS=$BASELOC/cosmos/$ARCH
export RESULTS=$BASELOC/results
export PKG_CONFIG_PATH="$COSMOS/lib/pkgconfig:$COSMOS/share/pkgconfig:$COSMOS/share/pkg-config"
export PKG_CONFIG_PATH_CUSTOM="$COSMOS/lib/pkgconfig:$COSMOS/share/pkgconfig:$COSMOS/share/pkg-config"
export ACLOCAL_PATH="$COSMOS/share/aclocal"

PREFIX="$COSMO/cosmocc/bin/$ARCH-unknown-cosmo"
export CC=$PREFIX-cc
export CXX=$PREFIX-c++
export LD=$PREFIX-ld
export OBJCOPY=$PREFIX-objcopy
export AR=$PREFIX-ar
export STRIP=$PREFIX-strip
export ZIPCOPY=$COSMO/o/tool/build/zipcopy
