#!/bin/sh
set -e
export STRIP="/bin/true"
alias strip=$STRIP
alias ar="$AR"

# why
cp -r "$BASELOC"/o/editor/vim/vim*/* ./

./configure --disable-darwin --disable-smack --disable-selinux\
    --disable-xsmp --enable-luainterp=no --enable-perlinterp=no\
    --enable-pythoninterp=no --enable-python3interp=no\
    --enable-tclinterp=no --enable-rubyinterp=no\
    --disable-netbeans --disable-cscope --enable-multibyte\
    --disable-xim --disable-fontset --enable-gui=no\
    --disable-nls --disable-sysmouse --disable-acl\
    --disable-canberra --disable-libsodium\
    --without-x --with-tlib=tinfo\
    --with-local-dir="$COSMOS"/lib\
    --sysconfdir=/zip --datarootdir=/zip/usr/share\
    --prefix="$COSMOS"\
    CFLAGS="-Os -I$COSMOS/include" LDFLAGS="-L$COSMOS/lib" 
