#!/usr/bin/env bash
set -e
shopt -s expand_aliases
export COSMOPOLITAN_DISABLE_ZIPOS=1

ARCH="${ARCH:-x86_64}"
alias strip="$STRIP"
alias ar="$AR"

export GOBJECT_LIBS=""
export PKG_CONFIG=""
export LIBGNUTLS_CFLAGS="-I$COSMOS/include/gnutls -I$COSMOS/include/nettle"
export LIBGNUTLS_LIBS="-L$COSMOS/lib -lgnutls -lhogweed -lnettle -lgmp"

"$BASELOC"/o/editor/emacs/emacs*/configure --with-gnutls=ifavailable\
    --host="$ARCH"-linux-gnu --with-threads\
    --without-dbus --without-selinux\
    --with-file-notification=no --without-modules\
    --sysconfdir=/zip --datarootdir=/zip/usr/share\
    --libexecdir=/zip/"$ARCH" --prefix="$COSMOS"\
    CFLAGS="-Os -I$COSMOS/include/ncurses"
