#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd postgres*/
    # make V=0 -s -i clean || true
    # make V=0 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.postgresql.org/pub/source/v15.5/postgresql-15.5.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd postgres*/
cp $COSMOS/common.cache ./config.cache
./configure --cache-file=config.cache --prefix="$COSMOS"\
    --with-gnu-ld\
    --sysconfdir=/zip/share --datarootdir=/zip/share --build=$ARCH-linux-gnu\
    --disable-nls --disable-rpath\
    --disable-debug --disable-profiling --disable-coverage --disable-dtrace\
    --disable-tap-tests --disable-depend --disable-cassert --disable-thread-safety\
    --disable-largefile --without-llvm --without-icu --without-tcl\
    --without-perl --without-python --without-gssapi\
    --without-pam --without-bsd-auth --without-ldap --without-bonjour\
    --without-selinux --without-systemd --without-readline\
    --without-ossp-uuid --without-libxslt\
    --without-zlib --without-zstd --with-gnu-ld --with-ssl=openssl\
    CFLAGS="-Os" 

# run make and/or make install
make -j$MAXPROC
make install -j$MAXPROC

echo "DONE."
