#!/usr/bin/env bash
set -e

alias strip='true'
export STRIP=""

$BASELOC/o/cli/zsh/zsh*/configure --prefix="$COSMOS" --disable-dynamic \
    --datarootdir=/zip/usr/share --with-tcsetpgrp --enable-gdbm \
    --enable-zshenv=/zip/etc/zshenv  --enable-zshrc=/zip/etc/zshrc \
    --enable-zprofile=/zip/etc/zprofile --enable-zlogin=/zip/etc/zlogin \
    --enable-zlogout=/zip/etc/zlogout \
    LDFLAGS="" \
    CFLAGS="-Os -I$COSMOS/include/ncurses -I$COSMOS/include/gdbm"

make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

# copy config files into /zip
mkdir -p /zip/etc
cp $BASELOC/cli/zsh/zshinit /zip/etc
for rcfile in z{sh{env,rc},profile,log{in,out}}; do
  echo ". /zip/etc/zshinit $rcfile" > /zip/etc/$rcfile
done
