#!/bin/sh
set -e

alias strip='true'
export STRIP=""

"$BASELOC"/o/cli/zsh/zsh*/configure --prefix="$COSMOS" --disable-dynamic \
    --datarootdir="$COSMOS"/share --with-tcsetpgrp --enable-gdbm \
    --enable-zshenv="$COSMOS"/etc/zshenv  --enable-zshrc="$COSMOS"/etc/zshrc \
    --enable-zprofile="$COSMOS"/etc/zprofile --enable-zlogin="$COSMOS"/etc/zlogin \
    --enable-zlogout="$COSMOS"/etc/zlogout \
    LDFLAGS="" \
    CFLAGS="-Os -I$COSMOS/include/ncurses -I$COSMOS/include/gdbm"

make V=0 -s -j"$MAXPROC"
make install V=0 -s -j"$MAXPROC"

# copy config files into "$COSMOS"
mkdir -p "$COSMOS"/etc
cp "$BASELOC"/cli/zsh/zshinit "$COSMOS"/etc

FILELIST='
zshenv
zshrc
zprofile
zlogin
zlogout
'

for rcfile in $FILELIST; do
  echo ". $COSMOS/etc/zshinit $rcfile" > "$COSMOS/etc/$rcfile"
done
