#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi


if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd gzip*/
    make V=1 -s -i clean || true
    make V=1 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd gzip*/
./configure --prefix="$COSMOS"\
    --datarootdir=/zip/share\
    CFLAGS="-Os"

# run make and/or make install
make V=1 -s -j$MAXPROC
make install V=1 -s -j$MAXPROC

echo "DONE."
