#!/bin/sh
set -e

export COSMOPOLITAN_DISABLE_ZIPOS=0
export ARCH=""

cd "$COSMO"
cp o/"$MODE"/third_party/bzip2/bzip2.dbg "$COSMOS"/bin/bzip2
cp o/"$MODE"/third_party/unzip/unzip.dbg "$COSMOS"/bin/unzip
cp o/"$MODE"/third_party/zip/zip.dbg "$COSMOS"/bin/zip
cp o/"$MODE"/third_party/zstd/zstd.dbg "$COSMOS"/bin/zstd

echo "DONE."
