#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.xz ]]; then
    # we already downloaded it
    cd mpfr*
    make -s -i clean || true
    make -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.xz -O sources.tar.xz
    tar -xf sources.tar.xz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd mpfr*
export PKG_CONFIG=""

./configure --prefix=$COSMOS\
    --disable-shared --disable-dependency-tracking --disable-silent-rules

# run make and/or make install
make -s -j2
make install -s -j2

echo "DONE."
