#!/bin/sh
set -e

export STRIP="/bin/true"

alias strip=$STRIP
alias ar="$AR"

export NCURSES_CONFIG="$COSMOS/bin/ncurses6-config"
export NCURSESW_CONFIG="$COSMOS/bin/ncurses6-config"
export NCURSESW_CFLAGS="-I$COSMOS/include/ncurses"
export NCURSESW_LIBS="-L$COSMOS/lib -lncurses -ltinfo"

"$BASELOC"/o/editor/nano/nano*/configure --sysconfdir="$COSMOS/share" --datarootdir="$COSMOS/share"\
    --prefix="$COSMOS"\
    --disable-nls --disable-rpath --disable-silent-rules\
    CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses"\
    LDFLAGS="-L$COSMOS/lib"
