#!/bin/sh
set -e

export STRIP="/bin/true"

alias strip=$STRIP
alias ar="$AR"

"$BASELOC"/o/editor/nano/nano*/configure --sysconfdir="$COSMOS/share" --datarootdir="$COSMOS/share"\
    --prefix="$COSMOS"\
    --disable-nls --disable-rpath --disable-silent-rules\
    --enable-color --enable-color --enable-utf8\
    CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses"\
    LDFLAGS="-L$COSMOS/lib"
