#!/usr/bin/env bash
set -e

export COSMOPOLITAN_DISABLE_ZIPOS=0
export ARCH=""

cd $COSMO
make m="$MODE" V=0 -s -j$MAXPROC \
    o/$MODE/third_party/zlib o/$MODE/third_party/zlib/gz o/$MODE/third_party/zstd\
    o/$MODE/third_party/sqlite3 o/$MODE/third_party/sqlite3/libsqlite3.a\
    o/$MODE/third_party/bzip2

