#!/usr/bin/env bash
set -e

cd $COSMO
make MODE="$MODE" V=0 -s -j$MAXPROC \
    toolchain\
    o/$MODE/third_party/zlib o/$MODE/third_party/zlib/gz o/$MODE/third_party/zstd\
    o/$MODE/third_party/sqlite3 o/$MODE/third_party/sqlite3/libsqlite3.a\
    o/$MODE/third_party/bzip2

