#!/bin/sh
set -e

# copy headers into cosmocc

mkdir -p "$COSMO"/cosmocc/include/third_party
cd "$COSMO"/cosmocc/include/third_party

SUBFOLDERS='
zlib
sqlite3
'

# don't copy core cosmo libs into $COSMOS, because
# cosmocc adds them via -L anyway
# cp $COSMO/cosmocc/$ARCH-linux-cosmo/lib/*.a $COSMOS/lib || true

for SUBFOLDER in $SUBFOLDERS; do
    mkdir -p "$SUBFOLDER"
    cp "$COSMO"/third_party/"$SUBFOLDER"/*.h ./"$SUBFOLDER" || true
    cp "$COSMO"/third_party/"$SUBFOLDER"/*.inc ./"$SUBFOLDER" || true
done

cd "$COSMOS"
for lib in crypt atomic gio-2.0 gobject-2.0 glib-2.0; do
    printf '\041\074\141\162\143\150\076\012' >"./lib/lib$lib.a"
done

if [ -f ./include/zlib.h ]; then
    echo "already have zlib.h"
else
    echo "#ifndef THIRD_PARTY_ZLIB_COSMOS" >./include/zlib.h
    echo "#define THIRD_PARTY_ZLIB_COSMOS" >>./include/zlib.h
    echo '#include "third_party/zlib/zlib.h"' >>./include/zlib.h
    echo "#ifdef THIRD_PARTY_ZLIB_COSMOS_GZ" >>./include/zlib.h
    echo '#include "third_party/zlib/gz/gzguts.inc"' >> ./include/zlib.h
    echo "#endif" >>./include/zlib.h
    echo '#define inflateBackInit(x, y, z) inflateBackInit_((x), (y), (z))' >> ./include/zlib.h
    echo "#endif" >>./include/zlib.h
fi

if [ -f ./lib/libz.a ]; then
    echo "already have libz.a"
else
    cp "$COSMO"/o/"$MODE"/third_party/zlib/zlib.a ./lib/libz.a
    $AR rcu ./lib/libz.a "$COSMO"/o/"$MODE"/third_party/zlib/gz/*.o
fi

cp "$COSMO"/o/"$MODE"/third_party/sqlite3/libsqlite3.a ./lib/libsqlite3.a
echo '#include "third_party/sqlite3/sqlite3.h"' > ./include/sqlite3.h
