#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

# download the source code
git clone --depth=1 --branch=datasette https://github.com/ahgamut/cpython datasette
# tar

# apply patches if any
# patch -p0 -i

# go into the source folder, configure
cd datasette
./configure --disable-shared --disable-loadable-sqlite-extensions\
    --with-lto=no --without-system-expat --without-system-ffi\
    --with-pymalloc --with-openssl=$COSMOS/ssl\
    --with-tzpath=/zip/usr/share/zoneinfo\
    --prefix=$COSMOS\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make -j2

echo "DONE."

