#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR
FOLDER="ncurses-6.4"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/ncurses/ncurses-6.4.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i
fi

# go into the source folder, configure
cd $FOLDER
./configure --without-libtool --without-shared\
    --without-ada --without-cxx --without-cxx-binding\
    --without-tests --with-termlib --with-ticlib\
    --without-dlsym --without-pcre2 --without-sysmouse\
    --with-curses-h --disable-stripping \
    --prefix=$COSMOS\
    --sysconfdir=/zip --datarootdir=/zip/share\
    CFLAGS="-Os"

# run make and/or make install
make -s -j2
make install -s -j2

echo "DONE."
