#!/usr/bin/env bash
set -e
shopt -s expand_aliases
export COSMOPOLITAN_DISABLE_ZIPOS=1

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR
FOLDER="emacs-29.1"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i distclean
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/emacs/emacs-29.1.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd $FOLDER
export GOBJECT_LIBS=""
export PKG_CONFIG=""

./configure --without-x --without-gnutls\
    --disable-acl --with-threads\
    --with-sound=no --with-unexec=no\
    --without-gpm --without-libgmp\
    --without-lcms2 --without-xpm --without-jpeg\
    --without-png --without-gif --without-tiff\
    --without-rsvg --without-libsystemd\
    --without-kerberos --without-kerberos5\
    --without-xft --without-harfbuzz\
    --without-gsettings --without-gconf\
    --without-cairo --without-xml2\
    --without-tiff --without-dbus --without-selinux\
    --without-modules\
    --sysconfdir=/zip --datarootdir=/zip/share\
    --libexecdir=/zip/$ARCH --prefix=$COSMOS\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
