#!/usr/bin/env bash
set -e
shopt -s expand_aliases
export COSMOPOLITAN_DISABLE_ZIPOS=1

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR
FOLDER="emacs-28.2"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/emacs/emacs-28.2.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd $FOLDER
./configure --without-x --without-gnutls\
    --disable-acl --with-threads\
    --with-sound=no --with-unexec=no\
    --without-gpm --without-modules --without-libgmp\
    --sysconfdir=/zip --datarootdir=/zip/share\
    --prefix=$COSMOS\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make -s -j2
make install -s -j2

echo "DONE."
