#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd links*/
    make V=0 -s -i clean || true
    make V=0 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q http://links.twibright.com/download/links-2.29.tar.gz -O sources.tar.gz
    tar -xf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd links*/
# cp $COSMOS/common.cache ./config.cache
./configure --prefix="$COSMOS"\
    --with-ssl="$COSMOS/ssl"\
    --datadir=/zip/usr/share --sysconfdir=/zip/usr/share\
    --without-openmp  --without-svgalib  --without-x\
    --without-fb      --without-directfb --without-pmshell\
    --without-windows --without-atheos   --without-haiku\
    --without-grx     --without-freetype --without-libjpeg\
    --without-libtiff --without-librsvg --without-libwebp\
    --without-libavif --disable-graphics --without-gpm\
    CFLAGS="-Os"


# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
