#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="xz-5.4.3"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean
    cd ..
else
    # download the source code
    wget -q https://sourceforge.net/projects/lzmautils/files/xz-5.4.3.tar.gz/download -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i
fi

# go into the source folder, configure
cd "$FOLDER"
./configure --prefix="$COSMOS"\
    --enable-shared=no --enable-static=yes\
    --disable-nls --disable-rpath\
    --without-pic --with-gnu-ld\
    --enable-sandbox=no\
    --sysconfdir=/zip --datarootdir=/zip/share\
    CFLAGS="-Os -std=gnu99"

# run make and/or make install
make -s -j
make install -s -j

echo "DONE."
