#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

# download the source code
wget -q https://ftp.gnu.org/gnu/wget/wget-1.21.tar.gz -O sources.tar.gz
tar -xzf sources.tar.gz

# apply patches if any
# disable all the checks in fseeko.c, and just call cosmo's fseeko
# remove the FALLTHROUGH macro if there is a complaint
patch -p0 -i minimal.diff

# go into the source folder, configure
cd wget*/

export OPENSSL_CFLAGS=""
export OPENSSL_LIBS="-lssl -lcrypto"

./configure --prefix="$COSMOS"\
    --with-ssl=openssl --with-openssl=yes\
    --without-pic --with-gnu-ld\
    --disable-shared --enable-static\
    --enable-threads=posix --disable-rpath\
    --disable-xattr --disable-nls\
    --without-plugin-support\
    --disable-pcre --disable-pcre2\
    --sysconfdir=/zip\
    CFLAGS="-Os" LIBS="-lbz2 -lz -llzma"

# run make and/or make install
make -s -j2
make install -s -j2

echo "DONE."
