#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd coreutils*/
    make V=1 -s -i clean || true
    make V=1 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/coreutils/coreutils-9.4.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd coreutils*/
./configure --prefix="$COSMOS"\
    --disable-nls --disable-dependency-tracking\
    --disable-silent-rules --disable-xattr\
    --disable-rpath --disable-acl --disable-assert\
    CFLAGS="-Os -I$COSMOS/include/ncurses"

# run make and/or make install
make V=1 -s -j$MAXPROC
make install V=1 -s -j$MAXPROC

echo "DONE."
