#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="libyaml-0.2.5"

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd libyaml*
    make -s -i clean
    cd ..
else
    # download the source code
    wget -q https://github.com/yaml/libyaml/archive/refs/tags/0.2.5.tar.gz -O sources.tar.gz
    tar -xzf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.patch
fi

# go into the source folder, configure
cd libyaml*
ls -al
autoreconf -fvi
./configure --without-pic --with-gnu-ld\
    --disable-shared --enable-static\
    --prefix=$COSMOS\
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
