#!/bin/sh
set -e

$BASELOC/o/lang/python/cpython*/configure --disable-shared --disable-loadable-sqlite-extensions\
    --with-lto=no --without-system-expat --without-system-ffi\
    --with-pymalloc --with-openssl="$COSMOS"/ssl\
    --disable-test-modules\
    --with-tzpath=/zip/usr/share/zoneinfo\
    --sysconfdir=/zip/usr/share --datarootdir=/zip/usr/share\
    --prefix="$COSMOS"\
    CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses -I$COSMOS/include/uuid"
