#!/usr/bin/env bash
set -e

../../tar*/configure --prefix="$COSMOS"\
    --disable-acl --disable-nls --disable-rpath\
    --without-posix-acls --without-selinux\
    --with-packager="cosmo" --without-xattrs\
    --with-gzip=gzip --with-xz=xz --datarootdir=/zip/usr/share\
    CFLAGS="-Os"
