#!/usr/bin/env bash
set -e
shopt -s expand_aliases

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then 
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then 
    echo "could not find COSMOS install directory!";
    exit 1
fi

alias strip=$STRIP
alias ar=$AR

if [[ -f sources.tar.gz ]]; then
    # we already downloaded it
    cd mpc*
    make V=0 -s -i clean || true
    make V=0 -s -i distclean || true
    cd ..
else
    # download the source code
    wget -q https://ftp.gnu.org/gnu/mpc/mpc-1.3.0.tar.gz -O sources.tar.gz
    tar -xf sources.tar.gz

    # apply patches if any
    # patch -p0 -i minimal.diff
fi

# go into the source folder, configure
cd mpc*
export PKG_CONFIG=""

cp ../saved_config.cache ./config.cache
./configure --cache-file=config.cache --prefix=$COSMOS\
    --disable-shared --disable-dependency-tracking --disable-silent-rules

# run make and/or make install
make V=0 -s -j$MAXPROC
make install V=0 -s -j$MAXPROC

echo "DONE."
